"""
SQLA Session protos
"""

from typing import Protocol


class DBSessionSync(Protocol):
    def add(self) -> None: ...
    def add_all(self) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class DBSessionAsync(Protocol):
    def add(self) -> None: ...
    def add_all(self) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
